
Traceback (most recent call last):
  File "tests/exceptions/backtrace/frame_values_backward.py", line 23, in <module>
    c(k)
  File "tests/exceptions/backtrace/frame_values_backward.py", line 20, in c
    b(n - 1)
> File "tests/exceptions/backtrace/frame_values_backward.py", line 16, in b
    a(n - 1)
  File "tests/exceptions/backtrace/frame_values_backward.py", line 12, in a
    1 / n
ZeroDivisionError: division by zero
