
[33m[1mTraceback (most recent call last):[0m

  File "[32mtests/exceptions/diagnose/[0m[32m[1msource_strings.py[0m", line [33m11[0m, in [35m<module>[0m
    [1ma[0m [35m[1m+[0m [36mb"prefix"[0m [35m[1m+[0m [36m'single'[0m [35m[1m+[0m [36m"""triple"""[0m [35m[1m+[0m [34m[1m1[0m [35m[1m+[0m [1mb[0m
    [36mâ”‚                                             â”” [0m[36m[1m0[0m
    [36mâ”” [0m[36m[1m0[0m

[31m[1mTypeError[0m:[1m unsupported operand type(s) for +: 'int' and 'bytes'[0m
